apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: rajdynacachetest
      app.kubernetes.io/component: rajdynacachetest
      app.kubernetes.io/instance: rajdynacachetest
    name: rajdynacachetest
  spec:
    replicas: 3
    selector:
      matchLabels:
        deployment: rajdynacachetest
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: rajdynacachetest
      spec:
        containers:
        - image: rajapiconnect1/rajdynacachetest:latest
          name: rajdynacachetest
          ports:
          - containerPort: 9443
            protocol: TCP
          - containerPort: 9080
            protocol: TCP
          resources: {}
        imagePullSecrets:
          - name: rajdockertest
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: rajdynacachetest
      app.kubernetes.io/component: rajdynacachetest
      app.kubernetes.io/instance: rajdynacachetest
    name: rajdynacachetest
  spec:
    ports:
    - name: 9080-tcp
      port: 9080
      protocol: TCP
      targetPort: 9080
    - name: 9443-tcp
      port: 9443
      protocol: TCP
      targetPort: 9443
    selector:
      deployment: rajdynacachetest
  status:
    loadBalancer: {}
kind: List
metadata: {}